# Generated by Django 2.2.24 on 2022-03-22 20:23

import colorful.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mayan.apps.databases.model_mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(db_index=True, help_text='A short text describing the theme.', max_length=128, unique=True, verbose_name='Label')),
                ('logo', models.TextField(blank=True, default='https://lh3.googleusercontent.com/fife/AAWUweULhkCLGFq9L8BUSFYnuWiRPhSp-dpqSnrRy3SlPKxp8u3Uiq_r_4otrCDMwaedmJZWi-9wgbTMtjQftF_n52djRhB84Ccosq93jAbSM4krlnVY4RxFUV02tsHSEjDy9pEcR8pyujKvJ47iwN_-Cn9h6f3jx7vhBXJY9pNtsss6uuuwjGitbGJbuka85LOhfmsLUPl_nWueZjo38mbtn2zFcBoGm-1-cqRQKClc6EzuhCSfK8R2Z17w969ix7f6dPQz7zNLlICtQa-yVTM_1Q-n7pYRDjSeKLsLybHKHSBOHi3755-uOQiA7wnj-_QCmVcSMYuWIid0Ih22AO8fUDtcLndssboU-Ne41XyY9v8mp0egQ4wYEn6QphN-9OR0m0mbf8yYSJpQ62ysiVPvsG671s25mlgnoiFmXeP2h2HLfPO2jVO4cYhzD1nV1Fvm5ACAJp9i0GVvuigDO4CB0sA20traVLs4R8oI9U5mwp48xsZYGz02Ib6whyKqZ8Bzb0K5T3su-bcE_OpCj4EpiJaG9O6A6syElXLCQPno_4RR9nijcEgtH2OVmz2a3SauETpOYnjbe3PisK8RnZBK7HIaB9k-LM8JrxEVBvvKG5Y7lFIsxkmg-JXlLFLCBzbSt_ys07Nari9AdCjSrBRVBgwy5X1cdqIAIHjSM1iJi1gZOJP6yLi6z6K5fp3Za86-DTJWnJR9PWvSUoyoijv5kfsHzF5f8ZVdWw=w1920-h955', help_text='The url to change your logo.', verbose_name='Logo')),
                ('stylesheet', models.TextField(blank=True, help_text='The CSS stylesheet to change the appearance of the different user interface elements.', verbose_name='Stylesheet')),
                ('navbarcolor', colorful.fields.RGBColorField(blank=True, help_text='Choose a color to change the navbar.', verbose_name='Navbar Color')),
                ('menucolor', colorful.fields.RGBColorField(blank=True, help_text='Choose a color to change the Menu.', verbose_name='Menu Color')),
            ],
            options={
                'verbose_name': 'Theme',
                'verbose_name_plural': 'Themes',
                'ordering': ('label',),
            },
            bases=(mayan.apps.databases.model_mixins.ExtraDataModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='UserThemeSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_setting', to='appearance.Theme', verbose_name='Theme')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='theme_settings', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User theme setting',
                'verbose_name_plural': 'User theme settings',
            },
        ),
    ]
