# Generated by Django 2.2.24 on 2022-03-21 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0005_auto_20220316_0407'),
        ('appearance', '0005_auto_20220309_0331'),
    ]

    operations = [
    ]
